<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ExpandDatosBasicosProduct</name>
   <tag></tag>
   <elementGuidId>e867f581-31cc-48b9-95eb-cd34abd4be6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-sm.btn-icon.btn-clean.btn-icon-md</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;subtype&quot;]/div/div[2]/div[1]/div[1]/div[1]/h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#basicData >> internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9b4333f6-b7cd-4f02-b15e-39fcd216f65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8b79defb-6903-4fa8-b602-e050c6323738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ktportlet-tool</name>
      <type>Main</type>
      <value>toggle</value>
      <webElementGuid>18da4cc0-74b6-43e7-a74b-9ec493688f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-icon btn-clean btn-icon-md</value>
      <webElementGuid>ef18d656-c0be-487c-bb26-61e3b0d19413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip_2mjn1vezqy</value>
      <webElementGuid>abd61982-b820-40ea-9a1b-28099170d61c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basicData&quot;)/div[@class=&quot;kt-portlet__head&quot;]/div[@class=&quot;kt-portlet__head-toolbar&quot;]/div[@class=&quot;kt-portlet__head-group&quot;]/a[@class=&quot;btn btn-sm btn-icon btn-clean btn-icon-md&quot;]</value>
      <webElementGuid>23aebd2d-666e-4662-a093-9962ef5db63d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='basicData']/div/div[2]/div/a</value>
      <webElementGuid>e6c6d1bf-5e60-4bf4-ac0f-32452ca5c953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos básicos'])[1]/following::a[1]</value>
      <webElementGuid>d6e2deb3-3c98-4729-b67f-c78d248f0ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clonar'])[1]/following::a[1]</value>
      <webElementGuid>7e87a857-58fd-4094-ac9d-7f979af03e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expand'])[1]/preceding::a[1]</value>
      <webElementGuid>a2442fcb-2a62-48d9-b736-94478dd451f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Código:'])[1]/preceding::a[1]</value>
      <webElementGuid>6d5416e8-20fb-4f4e-b07a-ba61c60b59a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>fb4dfe0a-eb16-46c5-ac07-de773410eb2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div/div[2]/div/a</value>
      <webElementGuid>7a1d4fe0-6c85-41de-8db5-580285a871ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#']</value>
      <webElementGuid>576a18f2-d046-4497-ba14-a978f29e1c42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
