<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IconoOjoHist</name>
   <tag></tag>
   <elementGuidId>0f44b82e-45b6-45e8-8254-778b47edb2ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;modal-historic&quot;]/div/div/div[2]/div[1]/div/div[2]/div[2]/div[2]/table/tbody/tr[1]/td[4]/a[count(. | //a[@class = 'btn btn-sm btn-clean btn-icon btn-icon-md show-product-version']) = count(//a[@class = 'btn btn-sm btn-clean btn-icon btn-icon-md show-product-version'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-sm.btn-clean.btn-icon.btn-icon-md.show-product-version > i.flaticon-eye</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-historic']/div/div/div[2]/div/div/div[2]/div[2]/div[2]/table/tbody/tr/td[4]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;2 04/12/2023 11:03:59 ADTestUser &quot;s] >> internal:attr=[title=&quot;Ver detalle&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b175d592-9bf7-49b7-883f-64bcbbe993bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-clean btn-icon btn-icon-md show-product-version</value>
      <webElementGuid>1d075462-709b-4a9c-8df2-2a0eadbbd453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;modal-historic&quot;]/div/div/div[2]/div[1]/div/div[2]/div[2]/div[2]/table/tbody/tr[1]/td[4]/a</value>
      <webElementGuid>f6333f86-5f50-42b6-94ef-ab270572b607</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-historic']/div/div/div[2]/div/div/div[2]/div[2]/div[2]/table/tbody/tr/td[4]/a/i</value>
      <webElementGuid>90a2c5cb-82c5-48a8-a008-8a7df1aab72b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/a/i</value>
      <webElementGuid>7f79cb7a-3858-4279-ba84-d5977dbacf69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
