<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IconoOjoProduct</name>
   <tag></tag>
   <elementGuidId>2bb40c4f-72ab-48ab-ae15-bace2baf44c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app&quot;]/div[2]/div/div/div[2]/div[2]/div[2]/table/tbody/tr[1]/td[7]/a[1][count(. | //a[@class = 'btn btn-sm btn-clean btn-icon btn-icon-md eye']) = count(//a[@class = 'btn btn-sm btn-clean btn-icon btn-icon-md eye'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-sm.btn-clean.btn-icon.btn-icon-md.show-product-version > i.flaticon-eye</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-historic']/div/div/div[2]/div/div/div[2]/div[2]/div[2]/table/tbody/tr/td[4]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;2 04/12/2023 11:03:59 ADTestUser &quot;s] >> internal:attr=[title=&quot;Ver detalle&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d4bb97b0-fda7-4259-84aa-bd03d253e0fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-clean btn-icon btn-icon-md eye</value>
      <webElementGuid>47c94782-8f8a-475d-8c5a-9ef24065590d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]/div[2]/div/div/div[2]/div[2]/div[2]/table/tbody/tr[1]/td[7]/a[1]</value>
      <webElementGuid>8457cc4f-7f76-4912-a9aa-0991cf13da9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-historic']/div/div/div[2]/div/div/div[2]/div[2]/div[2]/table/tbody/tr/td[4]/a/i</value>
      <webElementGuid>31490513-47d9-4894-837d-966cf1934799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/a/i</value>
      <webElementGuid>3955cd69-03e1-4589-b580-5f0ae66c694c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
