<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>bd90307c-2bde-41d4-b777-d988f7dca55a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='kt_login_signin_submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kt_login_signin_submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Login&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1c91a54c-0e1b-4353-977d-2ba5b6b4cd50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6a925c19-ee19-4e96-92ac-ccbe93fffb4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kt_login_signin_submit</value>
      <webElementGuid>9deca317-96d4-4995-b8e2-ea7529c07df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-brand btn-elevate kt-login__btn-primary</value>
      <webElementGuid>bdde0f86-dcb9-4433-9b65-7ba0e61524e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Login
                                </value>
      <webElementGuid>aed21976-e270-44c8-904e-2180824ed4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;wf-poppins-n3-active wf-poppins-n7-active wf-poppins-n5-active wf-poppins-n4-active wf-poppins-n6-active wf-active&quot;]/body[@class=&quot;kt-page--loading-enabled kt-quick-panel--right kt-demo-panel--right kt-offcanvas-panel--right kt-header--fixed kt-header--minimize-menu kt-header-mobile--fixed kt-subheader--enabled kt-subheader--transparent kt-aside--enabled kt-aside--left kt-aside--fixed&quot;]/div[@id=&quot;app&quot;]/div[@id=&quot;kt_login&quot;]/div[@class=&quot;kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor&quot;]/div[@class=&quot;kt-grid__item kt-grid__item--fluid kt-login__wrapper&quot;]/div[@class=&quot;kt-login__container&quot;]/div[@class=&quot;kt-login__signin&quot;]/form[@id=&quot;login-form&quot;]/div[@class=&quot;kt-login__actions&quot;]/button[@id=&quot;kt_login_signin_submit&quot;]</value>
      <webElementGuid>9d7547bc-8edf-4e35-843d-e9336ba6ded7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='kt_login_signin_submit']</value>
      <webElementGuid>f1579756-2f7d-4a44-bbd3-62b90d73fb58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div[4]/button</value>
      <webElementGuid>f675a845-7760-4eb9-a6fa-afc1f8d28d4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in to your account'])[1]/following::button[1]</value>
      <webElementGuid>111c4240-b552-4bc5-9c7c-c56407ea8217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in to your account'])[2]/preceding::button[1]</value>
      <webElementGuid>4befa35d-72c9-432b-a4aa-e4b5079fe8c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[4]/preceding::button[1]</value>
      <webElementGuid>eb91de3c-c702-4a28-87f7-fe94e8b54a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>f83656fe-1386-405b-b502-d4ef2f991d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'kt_login_signin_submit' and (text() = '
                                    Login
                                ' or . = '
                                    Login
                                ')]</value>
      <webElementGuid>8202cb64-3db2-42c1-8d88-71dd04221897</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
