<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select an option CANARY ISLAND</name>
   <tag></tag>
   <elementGuidId>c79a62d4-c1d3-4a44-8fd1-55e1b815e02c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='countryId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#countryId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d0043adf-b5b3-43e1-913c-4a366d340b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>countryId</value>
      <webElementGuid>3cd8ee9f-9557-421b-b336-3d2f4ed154ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_countryId</value>
      <webElementGuid>1517c48b-56db-4a94-ae59-edcdcc42f9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>0f65e508-6d37-475d-9016-a00b388fdd73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>42d51ae1-1b85-4bb2-8b7f-07cb548ec494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select an option CANARY ISLAND</value>
      <webElementGuid>c22d7c6c-b135-4cb1-aae8-d0c7953152d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;wf-poppins-n3-active wf-poppins-n7-active wf-poppins-n5-active wf-poppins-n4-active wf-poppins-n6-active wf-active&quot;]/body[@class=&quot;kt-page--loading-enabled kt-quick-panel--right kt-demo-panel--right kt-offcanvas-panel--right kt-header--fixed kt-header--minimize-menu kt-header-mobile--fixed kt-subheader--enabled kt-subheader--transparent kt-aside--enabled kt-aside--left kt-aside--fixed&quot;]/div[@id=&quot;app&quot;]/div[@id=&quot;kt_login&quot;]/div[@class=&quot;kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor&quot;]/div[@class=&quot;kt-grid__item kt-grid__item--fluid kt-login__wrapper&quot;]/div[@class=&quot;kt-login__container&quot;]/div[@class=&quot;kt-login__signin&quot;]/form[@id=&quot;login-form&quot;]/div[@class=&quot;input-group&quot;]/div[@class=&quot;input-group&quot;]/select[@id=&quot;countryId&quot;]</value>
      <webElementGuid>5a7172f0-9eaa-497e-81a6-4f6f66cb0d1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='countryId']</value>
      <webElementGuid>50e06e77-c529-46ef-89a1-b7967c6fc464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div[3]/div/select</value>
      <webElementGuid>04fd1fa2-eeb4-4e94-bdf1-cce09f208c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in to your account'])[1]/following::select[1]</value>
      <webElementGuid>ddc4344f-ec58-423a-9864-2a6349815b78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[2]/preceding::select[1]</value>
      <webElementGuid>f84b1c15-8f21-4d26-ab4c-8d56b0ca833d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in to your account'])[2]/preceding::select[1]</value>
      <webElementGuid>f752658d-1d31-4f47-b36b-d69f1c6182a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>042a3192-9a5c-4ce2-889a-8f5b09350e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'countryId' and @name = '_countryId' and (text() = 'Select an option CANARY ISLAND' or . = 'Select an option CANARY ISLAND')]</value>
      <webElementGuid>944eb5c6-276c-4657-838e-699ad9c33607</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
