<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Listado</name>
   <tag></tag>
   <elementGuidId>5efc0bb3-1322-4c49-bae4-d7f62b8824f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-secondary</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@class = 'btn btn-secondary' and (contains(text(), 'Listado') or contains(., 'Listado'))]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;kt_page_portlet&quot;]/div[3]/div[2]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Ir al listado&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3baa6021-dc30-4827-85c6-6cb283bc98f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary</value>
      <webElementGuid>2b836315-30d6-40f6-b4b8-9b106716c420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Listado</value>
      <webElementGuid>9c3aea42-e8b0-4425-97bc-6468c4c1a0b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_portlet&quot;)/div[@class=&quot;kt-portlet__foot&quot;]/div[@class=&quot;kt-form__actions kt-align-right&quot;]/a[@class=&quot;btn btn-secondary&quot;]</value>
      <webElementGuid>73101bd3-4abb-48c8-9ce8-545ae93c69b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_portlet']/div[3]/div/a</value>
      <webElementGuid>680d5851-26b8-4e5c-894f-15982986683d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ir al listado')]</value>
      <webElementGuid>f5f8b912-b276-42a9-98e1-8dd13e6e584b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CANCELLATION FEE LPA'])[1]/following::a[1]</value>
      <webElementGuid>bfcfdebb-2dee-4dbd-9453-d30133cd72a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tarifas:'])[1]/following::a[1]</value>
      <webElementGuid>4693e7df-359c-451c-8d63-c84ddbe045af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in to your account'])[1]/preceding::a[2]</value>
      <webElementGuid>30541fc1-27a7-4a93-a082-4578324a3b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[2]/preceding::a[2]</value>
      <webElementGuid>c7a9f597-fe71-47dd-bac1-c89d8346a98f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ir al listado']/parent::*</value>
      <webElementGuid>ddc79437-defd-45fb-b447-4dc1a9039700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>bc9ad24f-1cda-47de-94da-5761cdfa04a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Ir al listado' or . = 'Ir al listado')]</value>
      <webElementGuid>68f7cced-873f-4660-8587-66e1ae7b2457</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
