<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IconoHojaClonarComplemento</name>
   <tag></tag>
   <elementGuidId>e043f421-7f44-4d97-8587-bf6db70f0517</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//i[@class = 'flaticon2-copy']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(7) > a.btn.btn-sm.btn-clean.btn-icon.btn-icon-md.eye > i.flaticon-eye</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-history-complement']/div/div/div[2]/div/div[2]/div[2]/table/tbody/tr/td[7]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=dialog[name=&quot;Histórico del complemento&quot;i] >> internal:attr=[title=&quot;Ver detalle&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>47af1f99-26c8-4ad0-93a1-2ece83b25307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flaticon2-copy</value>
      <webElementGuid>8541094e-ff48-46f4-bb14-f36c47c4cb13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]/div[2]/div/div/div[2]/div[2]/div[2]/table/tbody/tr[1]/td[9]/a[4]/i</value>
      <webElementGuid>a99fa6bd-4c09-4695-afb6-12a2a9804681</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-history-complement']/div/div/div[2]/div/div[2]/div[2]/table/tbody/tr/td[7]/a/i</value>
      <webElementGuid>227e3b03-e272-472a-8f24-a47ab06137c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a/i</value>
      <webElementGuid>aaa35db3-16b7-4686-8e83-93139e994c2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
