<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IconoOjoHistoricoComplemento</name>
   <tag></tag>
   <elementGuidId>a6afd8b1-3af1-46eb-807b-db2417f72a0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;modal-history-complement&quot;]/div/div/div[2]/div[1]/div[2]/div[2]/table/tbody/tr/td[7]/a/i[count(. | //i[@class = 'flaticon-eye']) = count(//i[@class = 'flaticon-eye'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(7) > a.btn.btn-sm.btn-clean.btn-icon.btn-icon-md.eye > i.flaticon-eye</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-history-complement']/div/div/div[2]/div/div[2]/div[2]/table/tbody/tr/td[7]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=dialog[name=&quot;Histórico del complemento&quot;i] >> internal:attr=[title=&quot;Ver detalle&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>5470e10a-4855-42bb-9d22-c6aff32a54c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flaticon-eye</value>
      <webElementGuid>7830a0ae-16b3-44f7-8268-1463d47ec39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;modal-history-complement&quot;]/div/div/div[2]/div[1]/div[2]/div[2]/table/tbody/tr/td[7]/a/i</value>
      <webElementGuid>c1179b81-bbeb-4b48-a506-bb85d909fb7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-history-complement']/div/div/div[2]/div/div[2]/div[2]/table/tbody/tr/td[7]/a/i</value>
      <webElementGuid>54e2cd69-6dd2-4e35-bd29-c3a3d4299a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a/i</value>
      <webElementGuid>c1d85830-5dbb-42b0-9f4b-67e5ccb8e0ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
