<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Visualizarmodificar_ArtCompl</name>
   <tag></tag>
   <elementGuidId>145cf640-2594-4378-b36a-44e3899c823f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;kt_aside_menu&quot;]/ul/li[3]/div/ul/li[4]/div/ul/li[3]/a/span[2][count(. | //span[contains(@class, 'kt-menu__link-text') and (contains(text(), 'Visualizar/modificar') or contains(., 'Visualizar/modificar'))]) = count(//span[contains(@class, 'kt-menu__link-text') and (contains(text(), 'Visualizar/modificar') or contains(., 'Visualizar/modificar'))])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_aside_menu']/ul/li[3]/div/ul/li[3]/div/ul/li[3]/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Visualizar/modificar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>97064515-0af7-4132-b03b-0f8f2d929dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kt-menu__link-text</value>
      <webElementGuid>44e65da0-03fa-469b-9fc8-dc7de5e21643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Visualizar/modificar</value>
      <webElementGuid>67d8414f-50a2-4b03-b74e-778be508722a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;kt_aside_menu&quot;]/ul/li[3]/div/ul/li[4]/div/ul/li[3]/a/span[2]</value>
      <webElementGuid>43f30eb4-b625-4700-8d01-873d0eea0cda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_aside_menu']/ul/li[3]/div/ul/li[3]/div/ul/li[3]/a/span[2]</value>
      <webElementGuid>d967985a-b4f4-4ae2-af90-da16e8d0dce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crear'])[4]/following::span[2]</value>
      <webElementGuid>76f86dfa-bc16-4616-a648-3a22245087a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tarifa de complemento'])[2]/following::span[4]</value>
      <webElementGuid>afb19bca-d762-4e5e-9354-650b42db99ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artículos de complemento'])[1]/preceding::span[2]</value>
      <webElementGuid>ab5cfac2-d2f5-4227-a6d7-6c9e7158c43a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artículos de complemento'])[2]/preceding::span[4]</value>
      <webElementGuid>d8c3f4cd-6638-4bdf-92d6-c85e1d9ea9be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Visualizar/modificar']/parent::*</value>
      <webElementGuid>750c86ce-7ae2-4546-85f0-6d7c19403da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/ul/li[3]/div/ul/li[3]/a/span[2]</value>
      <webElementGuid>29210f47-fc79-4b4d-bacc-fd3e56975352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Visualizar/modificar' or . = 'Visualizar/modificar')]</value>
      <webElementGuid>1507a598-b7c9-46fb-b88e-395f2ea76ae6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
