<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Visualizarmodificar_TarifaCompl</name>
   <tag></tag>
   <elementGuidId>1d3e16c6-b166-4e35-96ac-aee72cf8704d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;kt_aside_menu&quot;]/ul/li[3]/div/ul/li[3]/div/ul/li[3]/a/span[2][count(. | //span[contains(@class, 'kt-menu__link-text') and (contains(text(), 'Visualizar/modificar') or contains(., 'Visualizar/modificar'))]) = count(//span[contains(@class, 'kt-menu__link-text') and (contains(text(), 'Visualizar/modificar') or contains(., 'Visualizar/modificar'))])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_aside_menu']/ul/li[3]/div/ul/li[3]/div/ul/li[3]/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Visualizar/modificar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7d4c4de2-d9a3-4fd3-8f53-b8c16d99352d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kt-menu__link-text</value>
      <webElementGuid>90c0269a-727e-4a79-b5e6-082cb9ba8ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Visualizar/modificar</value>
      <webElementGuid>7fdf60f4-e669-455c-9480-d9a8fd2ca275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;kt_aside_menu&quot;]/ul/li[3]/div/ul/li[3]/div/ul/li[3]/a/span[2]</value>
      <webElementGuid>2ff3fc6d-ead1-4f03-bd4a-75ece2a52a01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_aside_menu']/ul/li[3]/div/ul/li[3]/div/ul/li[3]/a/span[2]</value>
      <webElementGuid>bdaf91c3-e787-4640-9553-d1243dc3e227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crear'])[4]/following::span[2]</value>
      <webElementGuid>10094558-efe2-4880-90f2-d5bd8ab44606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tarifa de complemento'])[2]/following::span[4]</value>
      <webElementGuid>0a6b66f7-b4e7-4942-a9cf-fa47142e3d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artículos de complemento'])[1]/preceding::span[2]</value>
      <webElementGuid>b685272c-3cb4-49cf-99fe-a5638bdfb247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artículos de complemento'])[2]/preceding::span[4]</value>
      <webElementGuid>3f6fbbf7-a540-4305-b000-6c549aa84a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Visualizar/modificar']/parent::*</value>
      <webElementGuid>78b728a2-c5f6-48ef-842d-8e5c55f68292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/ul/li[3]/div/ul/li[3]/a/span[2]</value>
      <webElementGuid>194dcfbc-6436-4877-bef3-947960a03a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Visualizar/modificar' or . = 'Visualizar/modificar')]</value>
      <webElementGuid>940cb32b-d849-45db-aab6-55fbc52eae45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
