<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Visualizarmodificar_AgrupArtículos</name>
   <tag></tag>
   <elementGuidId>795b5056-005d-4133-aa3a-e7e2916902ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;kt_aside_menu&quot;]/ul/li[3]/div/ul/li[5]/div/ul/li[3]/a/span[2][count(. | //span[contains(@class, 'kt-menu__link-text') and (contains(text(), 'Visualizar/modificar') or contains(., 'Visualizar/modificar'))]) = count(//span[contains(@class, 'kt-menu__link-text') and (contains(text(), 'Visualizar/modificar') or contains(., 'Visualizar/modificar'))])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_aside_menu']/ul/li[3]/div/ul/li[3]/div/ul/li[3]/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Visualizar/modificar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e42b8c79-769e-434c-825e-a52ac418295a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kt-menu__link-text</value>
      <webElementGuid>f80b8c2f-79df-429b-accc-e6df155250dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Visualizar/modificar</value>
      <webElementGuid>faba94b8-c7f0-40f4-9f3a-522fb096ad51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;kt_aside_menu&quot;]/ul/li[3]/div/ul/li[5]/div/ul/li[3]/a/span[2]</value>
      <webElementGuid>a09fc406-cd62-4ab8-8bea-05b3c878309b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_aside_menu']/ul/li[3]/div/ul/li[3]/div/ul/li[3]/a/span[2]</value>
      <webElementGuid>b7162720-36d2-4cfe-86a7-a15dfa9fd7d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crear'])[4]/following::span[2]</value>
      <webElementGuid>749eb781-0947-43fd-9f1a-dfcb13737753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tarifa de complemento'])[2]/following::span[4]</value>
      <webElementGuid>0b419684-e4d7-4821-92ed-2d100b55ec59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artículos de complemento'])[1]/preceding::span[2]</value>
      <webElementGuid>d307a747-465c-4baf-b7b7-3aa7a46a68f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artículos de complemento'])[2]/preceding::span[4]</value>
      <webElementGuid>327839d6-5c28-4d4b-b138-0258b1628c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Visualizar/modificar']/parent::*</value>
      <webElementGuid>88aa554f-1a80-42d1-97d0-921c2f8c000e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/ul/li[3]/div/ul/li[3]/a/span[2]</value>
      <webElementGuid>faad369b-c9b3-4076-bc1e-f3850c730d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Visualizar/modificar' or . = 'Visualizar/modificar')]</value>
      <webElementGuid>56823b81-fa67-4b92-9b59-7da7e0d9c51c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
