<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Modificaciones</name>
   <tag></tag>
   <elementGuidId>638f7d30-016e-48c4-8ef8-1d9c116d7c0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(@class, 'kt-menu__link-text') and (contains(text(), 'Modificaciones') or contains(., 'Modificaciones'))]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_aside_menu']/ul/li[3]/div/ul/li[3]/div/ul/li[3]/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Visualizar/modificar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>471ed74a-7cfe-4a46-b97f-3af65059a1ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kt-menu__link-text</value>
      <webElementGuid>eddfb46e-256a-4015-910c-d811ca6299ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Modificaciones</value>
      <webElementGuid>2cfb1205-95d7-475c-b403-3b3bd33e5e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;kt_aside_menu&quot;]/ul/li[4]/div/ul/li[2]/div/ul/li[3]/a/span[2]</value>
      <webElementGuid>109dd765-7180-4a3c-995b-6dfa77565aeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_aside_menu']/ul/li[3]/div/ul/li[3]/div/ul/li[3]/a/span[2]</value>
      <webElementGuid>24f4c36d-ffc3-437b-8ed1-5185ad0bcc29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crear'])[4]/following::span[2]</value>
      <webElementGuid>6802aa72-5378-4392-89df-535d5b5d705d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tarifa de complemento'])[2]/following::span[4]</value>
      <webElementGuid>6e959101-b612-4591-92d6-05a11a61b372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artículos de complemento'])[1]/preceding::span[2]</value>
      <webElementGuid>b528ab89-6b6b-4e22-b2dc-4998b8ffde1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artículos de complemento'])[2]/preceding::span[4]</value>
      <webElementGuid>5b85553a-ad03-43b0-b3f0-63b0d6087533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Visualizar/modificar']/parent::*</value>
      <webElementGuid>306366dd-c69f-4512-84e7-03f186ef4f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/ul/li[3]/div/ul/li[3]/a/span[2]</value>
      <webElementGuid>08082727-82ba-48e8-acfd-509327edf767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Visualizar/modificar' or . = 'Visualizar/modificar')]</value>
      <webElementGuid>8326d627-a5b4-4d9d-a0bd-60bdd446be1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
