name: Ejecutar pruebas Katalon

on:
  schedule:
    - cron: '0 21 */7 * *' # Cada 7 días a las 21:00 (hora UTC)
  workflow_dispatch: # Para permitir ejecución manual

jobs:
  run-katalon-tests:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout código fuente
      - name: Checkout código fuente
        uses: actions/checkout@v2

      # Paso 2: Verificación del entorno host
      - name: Verificación del entorno host
        run: |
          echo "=== VERIFICACIÓN DEL ENTORNO HOST ==="
          pwd
          ls -la

      # Paso 3: Construir y ejecutar Docker
      - name: Construir y ejecutar Docker
        env:
          KATALON_API_KEY: ${{ secrets.KATALON_API_KEY }}
        run: |
          echo "=== CONSTRUYENDO IMAGEN ==="
          docker build -t katalon-test -f .github/Dockerfile .
          
          echo "=== EJECUTANDO CONTENEDOR ==="
          docker run --rm \
            -e KATALON_API_KEY="${KATALON_API_KEY}" \
            katalon-test

      # Paso 4: Subir resultados al repositorio
      - name: Subir resultados
        if: always()
        run: |
          git config --global user.name "afdediego"
          git config --global user.email "afdediego@gmail.com"
          git add -f Reports/
          git commit -m "Resultados de las pruebas [skip ci]" || echo "No hay cambios que commitear"
          git push || echo "No hay cambios que pushear"
