name: Ejecutar pruebas Katalon

on:
  schedule:
    - cron: '0 21 */7 * *' # Cada dos días a las 21:00 (hora UTC)
  workflow_dispatch: # Para permitir ejecución manual

jobs:
  run-katalon-tests:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout código fuente
      - name: Checkout código fuente
        uses: actions/checkout@v3

      # Paso 2: Construir y ejecutar Docker
      - name: Construir y ejecutar Docker
        run: |
          docker build -t katalon-test -f .github/Dockerfile .
          docker run --rm \
            --privileged \
            -e VPN_PASSWORD=${{ secrets.VPN_PASSWORD }} \
            -v $(pwd):/katalon/katalon/source \
            katalon-test

      # Paso 4: Subir resultados al repositorio
      - name: Subir resultados
        run: |
          git config --global user.name "afdediego"
          git config --global user.email "afdediego@gmail.com"
          git add Reports/
          git commit -m "Resultados de las pruebas"
          git push
