name: Ejecutar pruebas Katalon

on:
  schedule:
    - cron: '0 21 */7 * *' # Cada 7 días a las 21:00 (hora UTC)
  workflow_dispatch: # Para permitir ejecución manual

jobs:
  run-katalon-tests:
    runs-on: ubuntu-20.04

    steps:
      # Paso 1: Checkout código fuente
      - name: Checkout código fuente
        uses: actions/checkout@v3

      # Paso 2: Construir y ejecutar Docker
      - name: Construir y ejecutar Docker
        env:
          DOCKER_BUILDKIT: 1
        run: |
          echo "=== VERIFICACIÓN DEL ENTORNO HOST ==="
          pwd
          ls -la
          
          echo "=== CONSTRUYENDO IMAGEN ==="
          docker build --platform linux/amd64 -t katalon-test -f .github/Dockerfile .
          
          echo "=== EJECUTANDO CONTENEDOR ==="
          docker run --rm \
            --platform linux/amd64 \
            --network=host \
            --shm-size=4g \
            -e KATALON_API_KEY=${{ secrets.KATALON_API_KEY }} \
            -v "${PWD}:/katalon/source" \
            -v "${PWD}/Reports:/katalon/Reports" \
            --workdir=/katalon/source \
            katalon-test

      # Paso 3: Subir resultados al repositorio
      - name: Subir resultados
        if: always()
        run: |
          git config --global user.name "afdediego"
          git config --global user.email "afdediego@gmail.com"
          git add -f Reports/
          git commit -m "Resultados de las pruebas [skip ci]" || echo "No hay cambios que commitear"
          git push || echo "No hay cambios que pushear"
