name: Ejecutar pruebas Katalon

on:
  schedule:
    - cron: '0 21 */2 * *' # Cada dos días a las 21:00 (hora UTC)
  workflow_dispatch: # Permitir ejecución manual

jobs:
  run-katalon-tests:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código fuente desde el repositorio
      - name: Checkout código fuente
        uses: actions/checkout@v3

      # Paso 2: Levantar la VPN usando Docker
      - name: Levantar VPN
        run: |
          docker run -d --name vpn-container --rm my-vpn-image \
            --config /path/to/vpn/config.ovpn \
            --env VPN_USERNAME="ext_adiego@primeit.es" \
            --env VPN_PASSWORD="your_password_here"

      # Paso 3: Ejecutar Katalon con Docker
      - name: Ejecutar pruebas con Katalon
        run: |
          docker run --rm -v $(pwd):/katalon/katalon/source katalonstudio/katalon:latest \
            katalonc -noSplash -runMode=console \
            -projectPath=/katalon/katalon/source/"Pricing-Test Plan de Regresión.prj" \
            -testSuitePath="Test Suites/PRICING-Test Plan Regresión Core" \
            -browserType="Chrome (headless)"

      # Paso 4: Subir resultados al repositorio
      - name: Subir resultados
        run: |
          git config --global user.name "afdediego"
          git config --global user.email "afdediego@gmail.com"
          git add Reports/
          git commit -m "Resultados de las pruebas"
          git push https://github.com/afdediego/autokatalonpricing.git
