name: Ejecutar pruebas Katalon

on:
  schedule:
    - cron: '0 21 */7 * *' # Cada dos días a las 21:00 (hora UTC)
  workflow_dispatch: # Para permitir ejecución manual

jobs:
  run-katalon-tests:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout código fuente
      - name: Checkout código fuente
        uses: actions/checkout@v3

      # Paso 2: Configurar VPN
      - name: Configurar VPN
        run: |
          sudo apt-get update
          sudo apt-get install -y openvpn
          sudo openvpn --config .github/vpn-config.ovpn --auth-user-pass .github/auth.txt --daemon
        env:
          OVPN_CONFIG: .github/vpn-config.ovpn
          OVPN_AUTH: .github/auth.txt

      # Paso 3: Descargar y ejecutar Katalon en Docker
      - name: Descargar y ejecutar Katalon
        run: |
          docker run --rm \
          -v $(pwd):/katalon/katalon/source:ro \
          katalonstudio/katalon \
          katalon -noSplash -runMode=console \
          -projectPath="/katalon/katalon/source/Pricing-Test Plan de Regresión" \
          -testSuitePath="Test Suites/PRICING-Test Plan Regresión Core" \
          -browserType="Chrome (headless)"

      # Paso 4: Subir resultados al repositorio
      - name: Subir resultados
        run: |
          git config --global user.name "afdediego"
          git config --global user.email "afdediego@gmail.com"
          git add Reports/
          git commit -m "Resultados de las pruebas"
          git push
