name: Ejecutar pruebas Katalon

on:
  schedule:
    - cron: '0 21 */2 * *' # Cada dos días a las 21:00 (hora UTC)
  workflow_dispatch: # Para permitir ejecución manual

jobs:
  run-katalon-tests:
    runs-on: self-hosted

    steps:
      # Paso 1: Checkout código fuente
      - name: Checkout código fuente
        uses: actions/checkout@v3

      # Paso 2: Ejecutar pruebas con Katalon
      - name: Ejecutar pruebas con Katalon
        run: |
          /Applications/Katalon\ Studio\ Free\ Arm64.app/Contents/MacOS/katalon \
          -noSplash -runMode=console \
          -projectPath="$(pwd)/Pricing-Test Plan de Regresión" \
          -testSuitePath="Test Suites/PRICING-Test Plan Regresión Core" \
          -browserType="Chrome (headless)"

      # Paso 3: Subir resultados al repositorio
      - name: Subir resultados
        run: |
          git config --global user.name "afdediego"
          git config --global user.email "afdediego@gmail.com"
          git add Reports/
          git commit -m "Resultados de las pruebas"
          git push https://github.com/afdediego/autokatalonpricing.git
