<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>c7216ba9-40ec-46e2-b41f-77f49a8e2021</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_aside_brand']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.kt-aside__brand-logo > img[alt=&quot;Record go&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Record go&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bec023ec-5bcd-4448-ab81-26514fb9e182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Record go</value>
      <webElementGuid>891cbed4-30c0-40df-a221-5a398c42e819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/recordWhite-pre.png</value>
      <webElementGuid>6a909802-ce86-46c8-aea0-23882d8e6731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_aside_brand&quot;)/div[@class=&quot;kt-aside__brand-logo&quot;]/img[1]</value>
      <webElementGuid>bd9cb778-3db8-423f-8e4d-f1360b24c460</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_aside_brand']/div/img</value>
      <webElementGuid>6229bc7b-25d7-4af9-9401-69c5c2f0bb87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Record go'])[2]</value>
      <webElementGuid>3b999102-7650-43ad-85e5-854c57c8e13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/img</value>
      <webElementGuid>fdf60f25-3606-4d86-be69-28282cb68dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Record go' and @src = '/img/recordWhite-pre.png']</value>
      <webElementGuid>0e4ee36e-4ab9-4bc7-953f-fe3fa846a38f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
